set PART xc7a35tcpg236-1
set OUT_DIR reports/vector_stage7
file mkdir $OUT_DIR
foreach f {vector_register_file vector_alu vector_execution_unit vector_instruction_decoder vector_instruction_execution_unit vector_instruction_memory vector_program_core vector_data_memory vector_memory_instruction_decoder vector_memory_program_core vector_memory_program_core_synth_top} {read_verilog -sv rtl/$f.sv}
read_xdc constraints/vector_memory_program_core_stage7.xdc
synth_design -top vector_memory_program_core_synth_top -part $PART
report_utilization -hierarchical -file $OUT_DIR/stage7_synth_utilization.rpt
report_ram_utilization -file $OUT_DIR/stage7_ram_utilization.rpt
report_timing_summary -file $OUT_DIR/stage7_synth_timing_summary.rpt
puts "STAGE7_SYNTHESIS_COMPLETE"
