`timescale 1ns/1ps
module vector_stage11_stage12_equivalence_tb;
 logic clk=0,rst=0,start=0; always #5 clk=~clk;
 logic [4:0] program_length; logic runA,doneA,runB,doneB; logic [3:0] pcA,pcB; logic [15:0] insA,insB; logic valA,valB;
 logic prog_load_enable=0; logic [3:0] prog_load_addr; logic [15:0] prog_load_data; logic data_load_enable=0; logic [4:0] data_load_addr; logic [127:0] data_load_data;
 logic data_debug_read_enable=0; logic [4:0] data_debug_read_addr; logic [127:0] memA,memB; logic vector_load_enable=0; logic [2:0] vector_load_addr; logic [127:0] vector_load_data;
 logic debug_read_enable=0; logic [2:0] debug_read_addr; logic [127:0] regA,regB; logic [2:0] stateA,stateB;
 logic [31:0] x[0:31]; logic [31:0] reqA,hitA,missA,oaA,osA,depA,e0fA,e1fA,e0hA,e1hA,dupA;
 logic [31:0] reqB,hitB,missB,oaB,osB,araB,aphB; logic [2:0] unused;
 vector_extended_lookahead_program_core #(.LOOKAHEAD_DEPTH(6)) A(.clk(clk),.rst(rst),.start(start),.program_length(program_length),.running(runA),.done(doneA),.current_pc(pcA),.current_instruction(insA),.current_instruction_valid(valA),.prog_load_enable(prog_load_enable),.prog_load_addr(prog_load_addr),.prog_load_data(prog_load_data),.data_load_enable(data_load_enable),.data_load_addr(data_load_addr),.data_load_data(data_load_data),.data_debug_read_enable(data_debug_read_enable),.data_debug_read_addr(data_debug_read_addr),.data_debug_read_data(memA),.vector_load_enable(vector_load_enable),.vector_load_addr(vector_load_addr),.vector_load_data(vector_load_data),.debug_read_enable(debug_read_enable),.debug_read_addr(debug_read_addr),.debug_read_data(regA),.state_debug(stateA),.prefetch_request_count(reqA),.prefetch_hit_count(hitA),.prefetch_miss_count(missA),.entry0_hit_count(e0hA),.entry1_hit_count(e1hA),.overlap_alu_count(oaA),.overlap_store_count(osA),.dependency_blocked_count(depA),.entry0_fill_count(e0fA),.entry1_fill_count(e1fA),.duplicate_suppression_count(dupA),.debug_entry0_valid(),.debug_entry1_valid(),.debug_entry0_addr(),.debug_entry1_addr(),.debug_entry0_data(),.debug_entry1_data(),.debug_pending_read_valid());
 vector_two_outstanding_prefetch_program_core #(.LOOKAHEAD_DEPTH(6)) B(.clk(clk),.rst(rst),.start(start),.program_length(program_length),.running(runB),.done(doneB),.current_pc(pcB),.current_instruction(insB),.current_instruction_valid(valB),.prog_load_enable(prog_load_enable),.prog_load_addr(prog_load_addr),.prog_load_data(prog_load_data),.data_load_enable(data_load_enable),.data_load_addr(data_load_addr),.data_load_data(data_load_data),.data_debug_read_enable(data_debug_read_enable),.data_debug_read_addr(data_debug_read_addr),.data_debug_read_data(memB),.vector_load_enable(vector_load_enable),.vector_load_addr(vector_load_addr),.vector_load_data(vector_load_data),.debug_read_enable(debug_read_enable),.debug_read_addr(debug_read_addr),.debug_read_data(regB),.state_debug(stateB),.prefetch_request_count(reqB),.prefetch_hit_count(hitB),.prefetch_miss_count(missB),.entry0_hit_count(),.entry1_hit_count(),.overlap_alu_count(araB),.overlap_store_count(osB),.dependency_blocked_count(),.entry0_fill_count(),.entry1_fill_count(),.duplicate_suppression_count(),.alu_read_overlap_count(),.alu_prefetch_hit_count(aphB),.debug_entry0_valid(),.debug_entry1_valid(),.debug_entry0_addr(),.debug_entry1_addr(),.debug_entry0_data(),.debug_entry1_data(),.debug_pending_read_valid());
 function automatic [15:0] alu(input [3:0]o,input [2:0]d,a,b);alu={o,d,a,b,3'b0};endfunction function automatic [15:0] ld(input [2:0]d,input [4:0]a);ld={4'ha,d,a,4'b0};endfunction function automatic [15:0] st(input [2:0]s,input [4:0]a);st={4'hb,s,a,4'b0};endfunction function automatic [127:0] p4(input [31:0]a,b,c,d);p4={d,c,b,a};endfunction
 integer tests=0,fail=0;
 task automatic reset_all;begin rst=1;@(posedge clk);#1;rst=0;end endtask task automatic li(input int a,input [15:0]v);begin prog_load_addr=a;prog_load_data=v;prog_load_enable=1;@(posedge clk);#1;prog_load_enable=0;end endtask task automatic lm(input [4:0]a,input [127:0]v);begin data_load_addr=a;data_load_data=v;data_load_enable=1;@(posedge clk);#1;data_load_enable=0;end endtask task automatic lv(input [2:0]a,input [127:0]v);begin vector_load_addr=a;vector_load_data=v;vector_load_enable=1;@(posedge clk);#1;vector_load_enable=0;end endtask
 task automatic run_both(input int n);integer c;begin program_length=n;start=1;@(posedge clk);#1;start=0;c=0;while((!doneA||!doneB)&&c<300)begin@(posedge clk);#1;c++;end if(!doneA||!doneB)begin fail++;$display("FAIL timeout");end end endtask
 task automatic finish_case(input int n,input string name,input [4:0] ma,input [127:0] me);logic ok;begin tests++;ok=doneA&&doneB&&(pcA==pcB);debug_read_enable=1;for(int i=0;i<8;i++)begin debug_read_addr=i;#0;if(regA!==regB)ok=0;end debug_read_enable=0;if(ma!=5'h1f)begin data_debug_read_addr=ma;data_debug_read_enable=1;@(posedge clk);#1;if(memA!==memB||memA!==me)ok=0;data_debug_read_enable=0;end if(ok)$display("PASS EQUIV %0d %s",n,name);else begin fail++;$display("FAIL EQUIV %0d %s pcA=%0d pcB=%0d",n,name,pcA,pcB);end end endtask
 initial begin logic [127:0]a,b,c;a=p4(1,2,3,4);b=p4(5,6,7,8);c=p4(9,10,11,12);
  reset_all;lv(1,a);lv(2,b);li(0,alu(0,3,1,2));li(1,alu(1,4,3,1));li(2,alu(4,5,4,2));run_both(3);finish_case(1,"dependent ALU",5'h1f,0);
  reset_all;lm(0,a);lm(1,b);li(0,ld(1,0));li(1,ld(2,1));li(2,alu(0,3,1,2));li(3,st(3,2));run_both(4);finish_case(2,"load load add store",2,p4(6,8,10,12));
  reset_all;lm(0,a);lm(1,b);lm(2,c);li(0,ld(1,0));li(1,st(1,5));li(2,ld(2,1));li(3,alu(4,3,1,2));li(4,st(3,6));li(5,ld(4,2));run_both(6);finish_case(3,"multiple memory",6,p4(4,4,4,12));
  reset_all;lm(5,a);lv(4,b);li(0,st(4,5));li(1,ld(1,5));run_both(2);finish_case(4,"store hazard",5,b);
  reset_all;lv(1,a);li(0,16'hc000);li(1,alu(0,2,1,1));run_both(2);finish_case(5,"invalid instruction",5'h1f,0);
  reset_all;lm(0,a);li(0,ld(1,0));run_both(1);lm(0,b);start=1;@(posedge clk);#1;start=0;run_both(1);finish_case(6,"restart",5'h1f,0);
  reset_all;lm(0,a);lv(2,p4(16'hff,16'h0f,16'hf0,16'hff00));li(0,ld(1,0));li(1,alu(4,3,1,2));li(2,st(3,2));run_both(3);finish_case(7,"XOR",2,p4(1^16'hff,2^16'h0f,3^16'hf0,4^16'hff00));
  reset_all;lm(0,p4(32'h80000000,32'h10,32'hffffffff,32'h7fffffff));lv(2,p4(1,1,1,1));li(0,ld(1,0));li(1,alu(9,3,1,2));li(2,st(3,2));run_both(3);finish_case(8,"VSRA",2,p4(32'hc0000000,32'h00000008,32'hffffffff,32'h3fffffff));
  reset_all;lm(4,a);lv(2,b);li(0,st(2,4));li(1,ld(1,4));run_both(2);finish_case(9,"current-store hazard",4,b);
  reset_all;lm(6,a);lv(3,b);li(0,alu(0,1,3,3));li(1,st(1,6));li(2,ld(2,6));run_both(3);finish_case(10,"intervening-store hazard",6,p4(10,12,14,16));
  $display("Equivalence tests run: %0d",tests);$display("Equivalence tests failed: %0d",fail);$finish;
 end
endmodule

