`timescale 1ns/1ps
module vector_stage14_bottleneck_analysis_tb;
  logic clk=0,rst=0,start=0; always #5 clk=~clk;
  logic [4:0] program_length; logic running,done; logic [3:0] current_pc; logic [15:0] current_instruction; logic current_instruction_valid;
  logic pe=0; logic [3:0] pa; logic [15:0] pd; logic de=0; logic [4:0] da; logic [127:0] dd; logic dre=0; logic [4:0] dra; logic [127:0] drd; logic ve=0; logic [2:0] va; logic [127:0] vd; logic re=0; logic [2:0] ra; logic [127:0] rd; logic [2:0] state_dbg;
  logic [31:0] req,hit,miss,e0h,e1h,oa,os,dep,e0f,e1f,dup,ar,aph; logic [31:0] lwo,lws,bdep,brf,succ,rf2,orhw,c2,second,pair; logic ev0,ev1,ep; logic [4:0] ea0,ea1; logic [127:0] ed0,ed1;
  vector_load_overlap_program_core #(.LOOKAHEAD_DEPTH(6)) dut(.clk(clk),.rst(rst),.start(start),.program_length(program_length),.running(running),.done(done),.current_pc(current_pc),.current_instruction(current_instruction),.current_instruction_valid(current_instruction_valid),.prog_load_enable(pe),.prog_load_addr(pa),.prog_load_data(pd),.data_load_enable(de),.data_load_addr(da),.data_load_data(dd),.data_debug_read_enable(dre),.data_debug_read_addr(dra),.data_debug_read_data(drd),.vector_load_enable(ve),.vector_load_addr(va),.vector_load_data(vd),.debug_read_enable(re),.debug_read_addr(ra),.debug_read_data(rd),.state_debug(state_dbg),.prefetch_request_count(req),.prefetch_hit_count(hit),.prefetch_miss_count(miss),.entry0_hit_count(e0h),.entry1_hit_count(e1h),.overlap_alu_count(oa),.overlap_store_count(os),.dependency_blocked_count(dep),.entry0_fill_count(e0f),.entry1_fill_count(e1f),.duplicate_suppression_count(dup),.alu_read_overlap_count(ar),.alu_prefetch_hit_count(aph),.debug_entry0_valid(ev0),.debug_entry1_valid(ev1),.debug_entry0_addr(ea0),.debug_entry1_addr(ea1),.debug_entry0_data(ed0),.debug_entry1_data(ed1),.debug_pending_read_valid(ep),.outstanding_read_high_watermark(orhw),.cycles_with_two_outstanding(c2),.second_request_while_first_pending_count(second),.pending0_stale_discard_count(),.pending1_stale_discard_count(),.two_outstanding_useful_pair_count(pair),.deep_prefetch_request_count(),.deep_prefetch_hit_count(),.max_lookahead_distance(),.load_writeback_overlap_count(lwo),.load_writeback_cycles_saved(lws),.blocked_by_dependency_count(bdep),.blocked_by_rf_write_conflict_count(brf),.successful_overlap_count(succ),.rf_double_write_attempt_count(rf2));
  function automatic [127:0] p4(input [31:0]a,b,c,d);p4={d,c,b,a};endfunction function automatic [15:0] alu(input [3:0]o,input [2:0]d,a,b);alu={o,d,a,b,3'b0};endfunction function automatic [15:0] ld(input [2:0]d,input [4:0]a);ld={4'ha,d,a,4'b0};endfunction function automatic [15:0] st(input [2:0]s,input [4:0]a);st={4'hb,s,a,4'b0};endfunction
  task automatic reset_core;begin rst=1;@(posedge clk);#1;rst=0;end endtask task automatic li(input integer i,input [15:0]x);begin pa=i;pd=x;pe=1;@(posedge clk);#1;pe=0;end endtask task automatic lm(input [4:0]i,input [127:0]x);begin da=i;dd=x;de=1;@(posedge clk);#1;de=0;end endtask task automatic lv(input [2:0]i,input [127:0]x);begin va=i;vd=x;ve=1;@(posedge clk);#1;ve=0;end endtask
  integer total,alu_n,hit_n,miss_n,wb_n,store_n,other_n,overlap_n,two_n,fail_account; logic capture,trace;
  task automatic clear;begin total=0;alu_n=0;hit_n=0;miss_n=0;wb_n=0;store_n=0;other_n=0;overlap_n=0;two_n=0;end endtask
  task automatic run(input integer n,input string name,output integer measured);integer c;begin clear;capture=1;program_length=n;start=1;@(posedge clk);#1;start=0;c=0;while(!done&&c<300)begin@(posedge clk);#1;c++;end capture=0;measured=c;$display("SUMMARY %s TOTAL=%0d ALU=%0d VLOAD_HIT=%0d VLOAD_MISS=%0d LOAD_WB=%0d VSTORE=%0d OTHER=%0d OVERLAP=%0d TWO_OUTSTANDING=%0d",name,total,alu_n,hit_n,miss_n,wb_n,store_n,other_n,overlap_n,two_n);if(total!=measured)begin fail_account=fail_account+1;$display("ACCOUNTING FAIL %s primary=%0d measured=%0d",name,total,measured);end end endtask
  always @(posedge clk) begin #1;if(capture&&(dut.running||dut.done))begin integer cls; total=total+1; cls=0; if(dut.state==2'b01)begin wb_n=wb_n+1;cls=1;end else if(dut.is_vload&&dut.prefetch_hit)begin hit_n=hit_n+1;cls=1;end else if(dut.is_vload&&dut.architectural_read_request)begin miss_n=miss_n+1;cls=1;end else if(dut.is_vstore)begin store_n=store_n+1;cls=1;end else if(dut.is_alu)begin alu_n=alu_n+1;cls=1;end if(!cls)other_n=other_n+1; if(dut.prefetch_issue)begin overlap_n=overlap_n+1;if(dut.pending0_valid)two_n=two_n+1;end if(trace)$display("CYCLE %0d PC=%0d STATE=%0d INSTR=%h CLASS=%s PREFETCH=%b PENDING0=%b PENDING1=%b E0=%b E1=%b",total,dut.current_pc,dut.state,dut.current_instruction,(dut.state==2'b01)?"VLOAD_WRITEBACK":(dut.is_vload&&dut.prefetch_hit)?"VLOAD_PREFETCH_HIT":(dut.is_vload&&dut.architectural_read_request)?"VLOAD_MISS_ISSUE":dut.is_vstore?"VSTORE_EXEC":dut.is_alu?"ALU_EXEC":"OTHER",dut.prefetch_issue,dut.pending0_valid,dut.pending1_valid,dut.entry0_valid,dut.entry1_valid);end end
  initial begin integer c; logic [127:0]a,b,mask; fail_account=0;capture=0;trace=0;a=p4(1,2,3,4);b=p4(5,6,7,8);mask=p4(32'hffff0000,32'h0000ffff,32'h00ff00ff,32'hff00ff00);
    reset_core;lv(1,a);lv(2,b);for(integer i=0;i<4;i++)li(i,alu(0,i+3,(i==0)?1:i+2,2));run(4,"REG_VADD",c);
    reset_core;trace=1;for(integer j=0;j<4;j++)begin lm(j,p4(j+1,j+2,j+3,j+4));lm(8+j,p4(10+j,20+j,30+j,40+j));li(4*j,ld(1,j));li(4*j+1,ld(2,8+j));li(4*j+2,alu(0,3,1,2));li(4*j+3,st(3,16+j));end run(16,"ARRAY_ADD",c);trace=0;
    reset_core;lv(2,mask);for(integer k=0;k<4;k++)begin lm(k,p4(k,k+1,k+2,k+3));li(3*k,ld(1,k));li(3*k+1,alu(4,3,1,2));li(3*k+2,st(3,16+k));end run(12,"XOR",c);
    reset_core;lv(2,p4(1,1,1,1));for(integer m=0;m<4;m++)begin lm(m,p4(32'h80000000+m,32'h1,32'hffffffff,32'h7fffffff));li(3*m,ld(1,m));li(3*m+1,alu(9,3,1,2));li(3*m+2,st(3,16+m));end run(12,"VSRA",c);
    $display("STAGE14_COUNTERS LOAD_WB_OVERLAP=%0d LOAD_WB_SAVED=%0d BLOCKED_DEP=%0d BLOCKED_RF=%0d RF_DOUBLE=%0d",lwo,lws,bdep,brf,rf2);if(fail_account==0)$display("STAGE14_ANALYSIS_PASS");else $fatal(1,"Stage14 accounting failed");$finish;end
endmodule
